import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            {/* Get started by editing&nbsp; */}
            S2SM&#170; Rules set by Whitestone Corp.
            {/* <code className={styles.code}>pages/index.tsx</code>&nbsp;    */}
            {/* &#8225;Subject to Strict Management<br/> and Control with -SMAC- */}
          </p>
          <div>
            <a
              href="https://dijitrend.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/assets/images/dijitrendLogo.svg"
                alt="Dijitrend Logo"
                className={styles.dijitrendLogo}
                width={130}
                height={38}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/assets/images/proactivejs.svg"
            alt="Next.js Logo"
            width={329}
            height={39}
            priority
          />


          <div className={styles.thirteen}>
            <Image
              src="/assets/images/version-tag.svg"
              alt="13"
              width={100}
              height={50}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Dokümanlar <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            &#45;Reaktif &#126;&#187; Proaktif Sistemi&#45; hakkında sıkça sorulan sorulara göz atabilisiniz. Fikir vermesi açısından en hızlı yöntemdir!&nbsp;
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Keşfet <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Proaktif sisteme geçiş hakkında daha fazla bilgi almak için &nbsp;ziyaret edebilirsiniz!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Şablonlar <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              "Reaktif Entegrasyon Sistem Teknik çevrim Erken Kategorizasyonu" -RESTçEK- Proaktif Şablonlarını Keşfedin! Proactive Integration System Technical Cycle Early Categorization PIST&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Dağıtım <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Reaktif Entegre Sistem Entegrasyonu Testleri -RESET- hakkında merak edilenler! Proaktif.js &nbsp;W-Core desteği kullanarak alt yapınıza URL tabanında paylaştırılabilir.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
